### ISSUE TITLE
Make a Simple login

### ISSUE THREAD

**Issue by isuruAb** [TechForUs/ElePath#1]
Make a simple login that user can login using username and password

**Comment by priyamalM** [comment]
are we using any frameworks or is it just php?

**Comment by isuruAb** [comment]
we are going to use laravel for this. @Patrikejane  @priyamalM  you guys can continue this.you guys can discuss about this in this gitter thannel [https://gitter.im/TechForUs/ElePath](https://gitter.im/TechForUs/ElePath)

**Comment by priyamalM** [comment]
![screen shot 2017-03-21 at 21 26 05](https://cloud.githubusercontent.com/assets/14792739/24156934/05276f44-0e7e-11e7-9815-4fe01b8c671c.png)
![screen shot 2017-03-21 at 21 26 33](https://cloud.githubusercontent.com/assets/14792739/24156936/05b4ec84-0e7e-11e7-9ca1-89915be3fe85.png)
![screen shot 2017-03-21 at 21 27 53](https://cloud.githubusercontent.com/assets/14792739/24156935/0551ef1c-0e7e-11e7-953a-c9374b3916dd.png)

user login is completed.. admin priviledges is required to create a new user,,
make a get request to this url  `defaultadmin` this will create a admin with 
username - madushanka.priyamal@yahoo.com
password - dh67cl

**Comment by isuruAb** [comment]
@priyamalM  /createuser gives me this page (redirect me to here)
![image](https://cloud.githubusercontent.com/assets/7692626/24158074/4692ec1c-0e81-11e7-96ad-52b6ce51309a.png)

**Comment by priyamalM** [comment]
you cant create a user without login to site ,, only admins can create an account for you,, login as a admin,,if you dont have a admin account make a request to the "defaultadmin" this will create an admin account,then go to "createuser"

**Comment by isuruAb** [comment]
@priyamalM  if you can add the installation process to readme file that will be easy for end user to setup ElePath
